updated central pipeline v6

diff --git a/.github/workflows/dynamicCICD.yml b/.github/workflows/dynamicCICD.yml
--- a/.github/workflows/dynamicCICD.yml
+++ b/.github/workflows/dynamicCICD.yml
@@ -78,7 +78,11 @@ jobs:
             if ! command -v dotnet &> /dev/null; then
               echo ".NET SDK not found. Installing .NET SDK..."
               # Install .NET SDK (example for Ubuntu)
-              wget https://dotnet.microsoft.com/download/dotnet -qO- | bash
+              sudo add-apt-repository ppa:dotnet/backports
+              sudo apt-get update && sudo apt-get install -y dotnet-sdk-9.0
+              sudo apt-get update && sudo apt-get install -y aspnetcore-runtime-9.0
+              # Verify dotnet installation
+              dotnet --version || { echo "ERROR: .NET SDK installation failed."; exit 1; }
             else
               echo ".NET SDK is already installed"
             fi
