updated central pipeline v15

diff --git a/.github/workflows/dynamicCICD.yml b/.github/workflows/dynamicCICD.yml
--- a/.github/workflows/dynamicCICD.yml
+++ b/.github/workflows/dynamicCICD.yml
@@ -171,7 +171,7 @@ jobs:
       # Docker Build Stage
       - name: Build Docker image
         run: |
-          docker build -t ${{ github.repository }}:${{ github.sha }} -f Dockerfile . || { echo "ERROR: Docker build failed. Exiting."; exit 1; }
+          docker build -t ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }} -f Dockerfile . || { echo "ERROR: Docker build failed. Exiting."; exit 1; }
 
       # Cache Trivy Docker image to avoid re-downloading it in every run
       - name: Cache Trivy Docker image
@@ -212,6 +212,11 @@ jobs:
             exit $TRIVY_EXIT_CODE  # Propagate the error code if something went wrong
           fi
 
+      # Docker Push Stage
+      - name: Push Docker image
+        run: |
+          docker push ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }} || { echo "ERROR: Docker push failed. Exiting."; exit 1; }
+
       # Deploy Docker image to Dev environment
       - name: Deploy Docker image to Dev environment
         if: env.ENVIRONMENT == 'dev'
@@ -220,23 +225,23 @@ jobs:
           ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no krishnakekan@CHL29 << 'EOF'
             # Pull the latest image
             echo "Pulling Docker image ${GITHUB_REPOSITORY}:${GITHUB_SHA}..."
-            docker pull ${{ github.repository }}:${{ github.sha }}
-      
+            docker pull ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }}
+
             # Run the container
             echo "Running the container..."
-            docker run -d -p 8080:80 --name ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:${{ github.sha }}
+            docker run -d -p 8080:80 --name ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }} ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }}
           EOF
           echo "Deployment to Dev environment complete."
-      
+
       # Deploy Docker image to Prod environment
       - name: Deploy Docker image to Prod environment
         if: env.ENVIRONMENT == 'prod'
         run: |
           # Set variables
-          CONTAINER_NAME="${{ github.repository }}:${{ github.sha }}"
-      
+          CONTAINER_NAME="${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }}"
+
           echo "Deploying Docker image to Prod environment..."
-      
+
           # SSH into the server and check if the container is running
           ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no krishnakekan@CHL29 << EOF
             # Check if the container is running or exists
@@ -247,14 +252,14 @@ jobs:
             else
               echo "No running container found with name ${CONTAINER_NAME}. Skipping stop/remove."
             fi
-      
+
             # Pull the latest image
             echo "Pulling the latest image..."
-            docker pull ${{ github.repository }}:${{ github.sha }}
-      
+            docker pull ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }}
+
             # Run the new container
             echo "Running the new container..."
-            docker run -d -p 8080:80 --name ${CONTAINER_NAME} ${{ github.repository }}:${{ github.sha }}
-      
+            docker run -d -p 8080:80 --name ${CONTAINER_NAME} ${{ env.REPO_NAME }}_${{ env.branch }}:${{ github.sha }}
+
           EOF
-          echo "Deployment to Prod environment complete."          
+          echo "Deployment to Prod environment complete."
